#add by lihaiyan 20150829 begin
#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += ili9881_hd720_dsi_vdo_yassy_E165L.o




#add by lihaiyan 20150829 end
