#add by liupeng 20150720 beign
#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += ili9881_hd720_dsi_vdo_txd_V310F.o
#add by liupeng 20150720 end



