#zhenglihong 20150707 add begin
#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += BU64291AF.o

#zhenglihong 20150707 add end
