## add by liupeng 20150907 begin
#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += nt35521s_hd720_dsi_vdo_txd_E167L_CU.o
## add by liupeng 20150907 end



