#wangkangmin 20150729 add begin
#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += DW9714AF.o

#wangkangmin 20150729 add end
