#liuying 20150721 add begin
#
# Makefile for misc devices that really don't fit anywhere else.
#

include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y				+= leds_strobe.o
#liuying 20150721 add end