#liuying 20150714 add begin
#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += WV511AF.o

#liuying 20150714 add end
