#hebiao 20151130 begin
#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += fl10802_fwvga_dsi_vdo_hsd.o


#hebiao 20151130 end

