##tuwenzan add at 20150805 begin
#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += nt35521s_hd720_dsi_vdo_txd_E169F.o

##tuwenzan add at 20150805 end


