#add by huangzhaosong 20150723 begin
#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += ili9881_hd720_dsi_vdo_yassy_E167L.o




#add by huangzhaosong 20150723 end
