##guohongjin 20150716 add tianma lcd code begin
#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += hx8394d_hd720_dsi_vdo_tianma.o

##guohongjin 20150716 add tianma lcd code end


