# hebiao 20151203 begin
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y				+= dummyds.o kd_camera_hw.o
# hebiao 20151203 end